# Generated by Django 3.2.3 on 2021-06-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210611_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='review',
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('Cross Border Transactions', 'Cross Border Transactions'), ('Corporate & Compliance', 'Corporate & Compliance'), ('Construction & Real Estate', 'Construction & Real Estate'), ('Commercial Transactions', 'Commercial Transactions'), ('Dispute Resolution', 'Dispute Resolution'), ('Employment & Labor', 'Employment & Labor')], default='Cross Border Transactions', max_length=30),
        ),
    ]
