# Generated by Django 3.2.3 on 2021-06-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210621_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('CBT', 'Cross Border Transactions'), ('CC', 'Corporate & Compliance'), ('CRE', 'Construction & Real Estate'), ('CT', 'Commercial Transactions'), ('DR', 'Dispute Resolution'), ('EL', 'Employment & Labor')], default='CBT', max_length=3),
        ),
    ]
