# Generated by Django 3.2.3 on 2021-07-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='heading',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='service',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='heading',
            field=models.CharField(default='', max_length=250),
        ),
    ]
