# Generated by Django 3.2.3 on 2021-07-31 16:14

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_client_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Seniors', 'Seniors'), ('Associates', 'Associates'), ('Off Councel', 'Off Councel')], default='Off Councel', max_length=11)),
                ('name', models.CharField(default='', max_length=100)),
                ('picture', models.ImageField(null=True, upload_to=base.models.upload_lawyer_image)),
                ('credentials', models.TextField(default='')),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
